INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (1, 'Alex Smith', 'Software Engineer', 57432.50);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (2, 'Jordan Johnson', 'Senior Engineer', 120345.75);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (3, 'Taylor Brown', 'QA Engineer', 65200.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (4, 'Morgan Taylor', 'DevOps Engineer', 98000.25);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (5, 'Casey Anderson', 'Product Manager', 110500.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (6, 'Riley Thomas', 'Project Manager', 105750.40);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (7, 'Sam Jackson', 'Business Analyst', 67000.10);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (8, 'Jamie White', 'Technical Lead', 135250.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (9, 'Avery Harris', 'Architect', 149900.95);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (10, 'Cameron Martin', 'Support Engineer', 48000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (11, 'Drew Thompson', 'Software Engineer', 65500.55);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (12, 'Quinn Garcia', 'Senior Engineer', 142300.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (13, 'Reese Martinez', 'QA Engineer', 59000.20);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (14, 'Rowan Robinson', 'DevOps Engineer', 89000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (15, 'Skyler Clark', 'Product Manager', 125000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (16, 'Parker Rodriguez', 'Project Manager', 98050.75);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (17, 'Blake Lewis', 'Business Analyst', 72000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (18, 'Hayden Lee', 'Technical Lead', 131000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (19, 'Kendall Walker', 'Architect', 155500.50);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (20, 'Logan Hall', 'Support Engineer', 45500.25);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (21, 'Alex Johnson', 'Software Engineer', 61000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (22, 'Jordan Brown', 'Senior Engineer', 118500.45);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (23, 'Taylor Anderson', 'QA Engineer', 63500.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (24, 'Morgan Thomas', 'DevOps Engineer', 94000.80);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (25, 'Casey Jackson', 'Product Manager', 112200.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (26, 'Riley White', 'Project Manager', 101300.30);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (27, 'Sam Harris', 'Business Analyst', 68900.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (28, 'Jamie Martin', 'Technical Lead', 127450.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (29, 'Avery Thompson', 'Architect', 147200.20);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (30, 'Cameron Garcia', 'Support Engineer', 49800.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (31, 'Drew Martinez', 'Software Engineer', 60500.75);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (32, 'Quinn Robinson', 'Senior Engineer', 139900.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (33, 'Reese Clark', 'QA Engineer', 57120.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (34, 'Rowan Rodriguez', 'DevOps Engineer', 86000.60);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (35, 'Skyler Lewis', 'Product Manager', 120000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (36, 'Parker Lee', 'Project Manager', 99000.99);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (37, 'Blake Walker', 'Business Analyst', 70350.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (38, 'Hayden Hall', 'Technical Lead', 133250.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (39, 'Kendall Smith', 'Architect', 151400.45);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (40, 'Logan Johnson', 'Support Engineer', 47250.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (41, 'Alex Brown', 'Software Engineer', 64000.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (42, 'Jordan Taylor', 'Senior Engineer', 121800.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (43, 'Taylor Anderson', 'QA Engineer', 62350.30);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (44, 'Morgan Martinez', 'DevOps Engineer', 95500.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (45, 'Casey Robinson', 'Product Manager', 116700.75);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (46, 'Riley Clark', 'Project Manager', 100450.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (47, 'Sam Rodriguez', 'Business Analyst', 68220.80);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (48, 'Jamie Lewis', 'Technical Lead', 129900.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (49, 'Avery Lee', 'Architect', 145600.00);
INSERT INTO employee_dtls (employee_id, employee_name, employee_designation, employee_salary) VALUES (50, 'Cameron Walker', 'Support Engineer', 51200.25);
